version: "3"
services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev

  app:
    build: ./
    command: ./app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres